/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceGrafica;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.JOptionPane;

import com.mysql.fabric.xmlrpc.base.Data;

import br.edu.utfpr.cm.es2.hemocentro.controller.DoadorController;
import br.edu.utfpr.cm.es2.hemocentro.entity.Doador;

/**
 *
 * @author LuanB
 */
public class GraphicInterface extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form GraphicInterface
     */
    public GraphicInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        doadorPanel = new javax.swing.JPanel();
        nomeTField = new javax.swing.JTextField();
        nomePaiTField = new javax.swing.JTextField();
        naturalidadeTField = new javax.swing.JTextField();
        nomeMaeTField = new javax.swing.JTextField();
        orgaoExpTField = new javax.swing.JTextField();
        profissaoTField = new javax.swing.JTextField();
        estadoCivilTField = new javax.swing.JTextField();
        ufTField = new javax.swing.JTextField();
        nDocumentoTField = new javax.swing.JTextField();
        trabalhoAttTField = new javax.swing.JTextField();
        endComTField = new javax.swing.JTextField();
        endResTField = new javax.swing.JTextField();
        emailTField = new javax.swing.JTextField();
        sexoCBox = new javax.swing.JComboBox<>();
        dataNascTField = new javax.swing.JFormattedTextField();
        cadastroButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        doadorPanel.setLayout(null);

        nomeTField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        nomeTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTFieldActionPerformed(evt);
            }
        });
        doadorPanel.add(nomeTField);
        nomeTField.setBounds(190, 140, 190, 25);

        nomePaiTField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        nomePaiTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomePaiTFieldActionPerformed(evt);
            }
        });
        doadorPanel.add(nomePaiTField);
        nomePaiTField.setBounds(190, 190, 190, 25);

        naturalidadeTField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        naturalidadeTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naturalidadeTFieldActionPerformed(evt);
            }
        });
        doadorPanel.add(naturalidadeTField);
        naturalidadeTField.setBounds(190, 340, 190, 25);

        nomeMaeTField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        nomeMaeTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeMaeTFieldActionPerformed(evt);
            }
        });
        doadorPanel.add(nomeMaeTField);
        nomeMaeTField.setBounds(190, 240, 190, 25);

        orgaoExpTField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        orgaoExpTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgaoExpTFieldActionPerformed(evt);
            }
        });
        doadorPanel.add(orgaoExpTField);
        orgaoExpTField.setBounds(190, 440, 190, 25);

        profissaoTField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        profissaoTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profissaoTFieldActionPerformed(evt);
            }
        });
        doadorPanel.add(profissaoTField);
        profissaoTField.setBounds(190, 540, 190, 25);

        estadoCivilTField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        estadoCivilTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoCivilTFieldActionPerformed(evt);
            }
        });
        doadorPanel.add(estadoCivilTField);
        estadoCivilTField.setBounds(190, 290, 190, 25);

        ufTField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        ufTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ufTFieldActionPerformed(evt);
            }
        });
        doadorPanel.add(ufTField);
        ufTField.setBounds(190, 390, 190, 25);

        nDocumentoTField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        nDocumentoTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nDocumentoTFieldActionPerformed(evt);
            }
        });
        doadorPanel.add(nDocumentoTField);
        nDocumentoTField.setBounds(190, 490, 190, 25);

        trabalhoAttTField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        trabalhoAttTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trabalhoAttTFieldActionPerformed(evt);
            }
        });
        doadorPanel.add(trabalhoAttTField);
        trabalhoAttTField.setBounds(580, 140, 190, 25);

        endComTField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        endComTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endComTFieldActionPerformed(evt);
            }
        });
        doadorPanel.add(endComTField);
        endComTField.setBounds(580, 190, 190, 25);

        endResTField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        endResTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endResTFieldActionPerformed(evt);
            }
        });
        doadorPanel.add(endResTField);
        endResTField.setBounds(580, 240, 190, 25);

        emailTField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        emailTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTFieldActionPerformed(evt);
            }
        });
        doadorPanel.add(emailTField);
        emailTField.setBounds(580, 290, 190, 25);

        sexoCBox.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        sexoCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        doadorPanel.add(sexoCBox);
        sexoCBox.setBounds(580, 390, 190, 25);

        dataNascTField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/M/yy"))));
        dataNascTField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        dataNascTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataNascTFieldActionPerformed(evt);
            }
        });
        doadorPanel.add(dataNascTField);
        dataNascTField.setBounds(580, 340, 190, 25);

        cadastroButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cadastroButton.setText("Cadastrar Doador");
        cadastroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					cadastroButtonActionPerformed(evt);
				} catch (ParseException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
        doadorPanel.add(cadastroButton);
        cadastroButton.setBounds(580, 490, 190, 27);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Nome :");
        doadorPanel.add(jLabel2);
        jLabel2.setBounds(130, 140, 50, 19);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Estado Civil :");
        doadorPanel.add(jLabel3);
        jLabel3.setBounds(100, 290, 90, 19);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("Naturalidade :");
        doadorPanel.add(jLabel4);
        jLabel4.setBounds(90, 340, 90, 19);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("UF :");
        doadorPanel.add(jLabel5);
        jLabel5.setBounds(150, 390, 28, 19);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("Nº Documento :");
        doadorPanel.add(jLabel6);
        jLabel6.setBounds(70, 490, 110, 19);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("Orgão Expedidor :");
        doadorPanel.add(jLabel7);
        jLabel7.setBounds(60, 440, 120, 19);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setText("Profissão :");
        doadorPanel.add(jLabel8);
        jLabel8.setBounds(110, 540, 70, 19);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel9.setText("Nome do Pai :");
        doadorPanel.add(jLabel9);
        jLabel9.setBounds(90, 190, 100, 19);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel10.setText("Nome da Mãe :");
        doadorPanel.add(jLabel10);
        jLabel10.setBounds(80, 240, 110, 19);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel11.setText("Sexo :");
        doadorPanel.add(jLabel11);
        jLabel11.setBounds(530, 390, 42, 19);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel12.setText("Data de Nascimento :");
        doadorPanel.add(jLabel12);
        jLabel12.setBounds(430, 340, 150, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Trabalho Atual :");
        doadorPanel.add(jLabel1);
        jLabel1.setBounds(470, 140, 110, 19);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel13.setText("Endereço Comercial :");
        doadorPanel.add(jLabel13);
        jLabel13.setBounds(440, 190, 137, 19);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel14.setText("Endereço Residencial :");
        doadorPanel.add(jLabel14);
        jLabel14.setBounds(430, 240, 150, 19);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel15.setText("E-mail :");
        doadorPanel.add(jLabel15);
        jLabel15.setBounds(520, 290, 50, 19);

        header.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        header.setText("Cadastro de Doadores");
        doadorPanel.add(header);
        header.setBounds(190, 40, 190, 60);
        
        //jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("C:\\Users\\LuanB\\Desktop\\Semestre 6\\Engenharia de Software 2\\Projeto1-ES2\\programa\\interfaceGrafica\\Blood-Bag.jpg"))); // NOI18N
        //jLabel16.setText("jLabel16");
        //doadorPanel.add(jLabel16);
        //jLabel16.setBounds(-70, 0, 990, 710);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(doadorPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(doadorPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void cadastroButtonActionPerformed(java.awt.event.ActionEvent evt) throws ParseException {                                               
        // TODO add your handling code here:
    	
    	DoadorController dc = new DoadorController();
    	Doador d = new Doador();
    	
    	if(dataNascTField.getText().isEmpty() || emailTField.getText().isEmpty() 
    			|| endComTField.getText().isEmpty() || endResTField.getText().isEmpty() 
    			|| estadoCivilTField.getText().isEmpty() || nDocumentoTField.getText().isEmpty() 
    			|| naturalidadeTField.getText().isEmpty() || nomeMaeTField.getText().isEmpty()
    			|| nomePaiTField.getText().isEmpty() || nomeTField.getText().isEmpty()
    			|| orgaoExpTField.getText().isEmpty() || profissaoTField.getText().isEmpty()
    			|| trabalhoAttTField.getText().isEmpty() || ufTField.getText().isEmpty()
    			){
    		JOptionPane.showMessageDialog(null, "Dados Insuficientes!");
    	}else{
    		
    		SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    		
    		Date dataDeNascimento = formato.parse(dataNascTField.getText());
    
    		d.setEmail(emailTField.getText());
    		d.setEnderecoComercial(endComTField.getText());
    		d.setEnderecoResidencial(endResTField.getText());
    		d.setEstadoCivil(estadoCivilTField.getText());
    		d.setNacionalidade("Brasil");
    		d.setNaturalidade( naturalidadeTField.getText());
    		d.setNome(nomeTField.getText());
    		d.setNomeDaMae(nomeMaeTField.getText());
    		d.setNomeDoPai(nomePaiTField.getText());
    		d.setOrgaoExpedidor(orgaoExpTField.getText());
    		d.setProfissao(profissaoTField.getText());
    		d.setSexo(sexoCBox.getSelectedItem().toString().charAt(0));
    		d.setTrabalhoAtual(trabalhoAttTField.getText());
    		d.setTypoDoDocumento('a');
    		d.setUf(ufTField.getText());
    		d.setDataDeNascimento(dataDeNascimento);
    		d.setNumeroDoDocumento(nDocumentoTField.getText());
    		
    		dc.persist(d);
    	}
    }                                              

    private void dataNascTFieldActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void emailTFieldActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void endResTFieldActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void endComTFieldActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void trabalhoAttTFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void nomeTFieldActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void nomePaiTFieldActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void nomeMaeTFieldActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void estadoCivilTFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void naturalidadeTFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void ufTFieldActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void orgaoExpTFieldActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void nDocumentoTFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void profissaoTFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    /**
     * @param args the command line arguments
     */
    /**
     * public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphicInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphicInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphicInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphicInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraphicInterface().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify                     
    private javax.swing.JButton cadastroButton;
    private javax.swing.JFormattedTextField dataNascTField;
    private javax.swing.JPanel doadorPanel;
    private javax.swing.JTextField emailTField;
    private javax.swing.JTextField endComTField;
    private javax.swing.JTextField endResTField;
    private javax.swing.JTextField estadoCivilTField;
    private javax.swing.JLabel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nDocumentoTField;
    private javax.swing.JTextField naturalidadeTField;
    private javax.swing.JTextField nomeMaeTField;
    private javax.swing.JTextField nomePaiTField;
    private javax.swing.JTextField nomeTField;
    private javax.swing.JTextField orgaoExpTField;
    private javax.swing.JTextField profissaoTField;
    private javax.swing.JComboBox<String> sexoCBox;
    private javax.swing.JTextField trabalhoAttTField;
    private javax.swing.JTextField ufTField;
    // End of variables declaration                   
}
